Jupyter notebook extending SimPy tutorial found at

https://realpython.com/simpy-simulating-with-python/

# 1.0 Introduction

## 1.1 Credits, Sources, and Inspirations

Tutorial

https://realpython.com/simpy-simulating-with-python/

## 1.2 Imports and Installs

In [1]:
#import sys
#!pip install simpy

In [2]:
import simpy
import random
import statistics

import pandas as pd
import numpy

# 2.0 Classes and Functions

## 2.1 Theater Class

In [3]:
class Theater(object):
    def __init__(self, env, num_cashiers, num_servers, num_ushers):
        self.env = env
        self.cashier = simpy.Resource(env,num_cashiers)
        self.server = simpy.Resource(env, num_servers)
        self.usher = simpy.Resource(env, num_ushers)
        
    def purchase_ticket(self, moviegoer):
        yield self.env.timeout(random.randint(1,3))
        
    def check_ticket(self, moviegoer):
        #note that the units are 1 and it takes 3 seconds to check a ticket
        yield self.env.timeout(3 / 60)
        
    def sell_food(self, moviegoer):
        yield self.env.timeout(random.randint(1,5))

## 2.2 Moviegoer functions

In [4]:
def go_to_movies(env, moviegoer, theater):
    #moviegoer arrives at the theater
    arrival_time = env.now
    
    #using with tells simpy to release resource when done
    with theater.cashier.request() as request:
        yield request
        yield env.process(theater.purchase_ticket(moviegoer))
        
    with theater.usher.request() as request:
        yield request
        yield env.process(theater.check_ticket(moviegoer))
        
    if random.choice([True, False]):
        with theater.server.request() as request:
            yield request
            yield env.process(theater.sell_food(moviegoer))
            
    #moviegoer goes into theater. wait time is over
    trial_wait_times.append(env.now - arrival_time)

## 2.3 Run the theater process

In [5]:
def run_theater(env, num_cashier, num_servers, num_ushers):
    theater = Theater(env, num_cashier, num_servers, num_ushers)
    
    #expect 3 people in line at box office open
    for moviegoer in range(3):
        env.process(go_to_movies(env, moviegoer, theater))
        
    while True:
        yield env.timeout(0.20)  #wait 12 seconds
        
        moviegoer +=1
        env.process(go_to_movies(env, moviegoer, theater))

## 2.4 Measurement functions

In [6]:
def get_average_wait_time(wait_times):
    return statistics.mean(wait_times)

In [7]:
def get_average_num_customers(num_cust):
    return statistics.mean(num_cust)

## 2.5 Simulation function

In [8]:
def run_sim(num_cashiers, num_servers, num_ushers):
    #setup 
    #seed set globally so we don't just run the same sim every time   
    
    #initialize the simpy environment
    env = simpy.Environment()
    env.process(run_theater(env, num_cashiers, num_servers, num_ushers))
    
    #run for 120 simulated minutes  (make a parameter later)
    env.run(until=90)
    
    #print(wait_times)
    #return the results
    return get_average_wait_time(trial_wait_times)

# 3.0 Run the simulation

At this level, we should explore the parameter space a bit. Since it is not a huge parameter space, some intelligently applied brute force should give us a lot of insight. To be "intelligent" the key is to think intuitively about the bottlenecks in the system.  Note individual process times:

- purchase between 1 and 3 minutes
- ticket validation 3 seconds 
- food selling .5 - 2.5 minutes 
- moviegoers arrive at the box office every 12 seconds (5 per minute)

---

1. One way we will extend upon the tutorial is looking at the number of moviegoers processed. Wait time is cool, but what really matters is getting people to pay for a ticket, and hopefully, buy some favorably priced concessions.

2. Note that as set up, we have 5 people arriving per minute. As I've extended the time from 90 minutes to 120 minutes, this means 600 people show up to see our movie.

In [9]:
sim_results = []

#note, do not set a universal seed within the runs else you just make a bunch of identical runs
random.seed(311)  #i love douglas adams as much as the next nerd but...

runs_per_config = 30

max_cashiers = 20
max_servers = 20
max_ushers = 10

In [10]:
for cashiers in range(1,max_cashiers+1):
    for servers in range(1,max_servers+1):
        for ushers in range(1,max_ushers+1):
            #initialize wait_times for this config
            config_wait_times = []
            config_num_customers = []
            
            for runs in range(1, runs_per_config+1):
                #(re-)initialize wait_times
                #initialize this trials wait times
                trial_wait_times = []

                #run the sim, returning average wait time and number of customers    
                trial_avg_wait = run_sim(cashiers, servers, ushers)
                #append to the configuration arrays so we can calculate over config
                
                #append the results
                config_wait_times.append(trial_avg_wait)
                config_num_customers.append(len(trial_wait_times))
                
            
            #now do the configuration aggregates and append to sim results    
            
            avg_wait = get_average_wait_time(config_wait_times)
            avg_num_cust = get_average_num_customers(config_num_customers)
                
            this_result = (cashiers, servers, ushers, avg_wait, avg_num_cust)
            sim_results.append(this_result)

In [11]:
#dump results into a dataframe
cols = ['cashiers', 'servers', 'ushers', 'avg_wait', 'num_customers']

sim_results_df = pd.DataFrame(sim_results, columns=cols)

sim_results_df.tail()

      cashiers  servers  ushers  avg_wait  num_customers
3995        20       20       6  3.439536          436.5
3996        20       20       7  3.414055          434.0
3997        20       20       8  3.509288          434.5
3998        20       20       9  3.481773          433.5
3999        20       20      10  3.333311          435.0

# 4.0 Apply business considerations and recommendations

## 4.1 Financial assumptions

To make this more concrete, let's add some businessconsiderations to the simulation.

- Average spend per moviegoer is 18 (the more advanced version will break this up into admission and concession)
- Cashiers cost 40 = 20 per hour x 2 hours
- Servers cost 35 = 17.5 per hour x 2 hours
- Ushers cost 30 = 15 per hour x 2 hours

In [12]:
rev_per_customer = 18

cost_cashier = 40
cost_server = 35
cost_usher = 30

## 4.2 Financial calculations

In [13]:
sim_results_df['revenue'] = sim_results_df['num_customers'] * rev_per_customer

sim_results_df['cost_cashiers'] = sim_results_df['cashiers'] * cost_cashier
sim_results_df['cost_servers'] = sim_results_df['servers'] * cost_server
sim_results_df['cost_ushers'] = sim_results_df['ushers'] * cost_usher

sim_results_df['cost_labor'] = (sim_results_df['cost_cashiers'] 
                                + sim_results_df['cost_servers']
                                + sim_results_df['cost_ushers'])

In [14]:
sim_results_df['profit'] = sim_results_df['revenue'] - sim_results_df['cost_labor']

In [15]:
sim_results_df.head()

,cashiers,servers,ushers,avg_wait,num_customers,revenue,cost_cashiers,cost_servers,cost_ushers,cost_labor,profit
0,1,1,1,43.183576,45.5,819.0,40,35,30,105,714.0
1,1,1,2,40.837356,39.5,711.0,40,35,60,135,576.0
2,1,1,3,45.037749,42.5,765.0,40,35,90,165,600.0
3,1,1,4,42.899659,48.5,873.0,40,35,120,195,678.0
4,1,1,5,42.923617,45.0,810.0,40,35,150,225,585.0

## 4.3 Profit and revenue analysis

For a quick analysis, sort by profit descending and show the top 25 results

In [16]:
sim_results_df.sort_values(by=['profit'], ascending=False).head(25)

,cashiers,servers,ushers,avg_wait,num_customers,revenue,cost_cashiers,cost_servers,cost_ushers,cost_labor,profit
2070,11,8,1,3.903373,435.0,7830.0,440,280,30,750,7080.0
2080,11,9,1,3.727435,435.5,7839.0,440,315,30,785,7054.0
2280,12,9,1,3.785861,435.0,7830.0,480,315,30,825,7005.0
2090,11,10,1,3.399573,434.5,7821.0,440,350,30,820,7001.0
2082,11,9,3,3.642818,434.5,7821.0,440,315,90,845,6976.0
2480,13,9,1,3.552692,435.5,7839.0,520,315,30,865,6974.0
2102,11,11,3,3.627143,438.0,7884.0,440,385,90,915,6969.0
1880,10,9,1,4.526245,428.5,7713.0,400,315,30,745,6968.0
2281,12,9,2,3.554947,434.5,7821.0,480,315,60,855,6966.0
1890,10,10,1,4.035123,430.0,7740.0,400,350,30,780,6960.0
1891,10,10,2,3.974066,431.5,7767.0,400,350,60,810,6957.0
2083,11,9,4,3.686586,435.0,7830.0,440,315,120,875,6955.0
2472,13,8,3,3.840847,435.5,7839.0,520,280,90,890,6949.0
2100,11,11,1,3.604214,433.5,7803.0,440,385,30,855,6948.0
2101,11,11,2,3.465774,435.0,7830.0,440,385,60,885,6945.0
2081,11,9,2,3.670497,431.0,7758.0,440,315,60,815,6943.0
2112,11,12,3,3.520507,438.5,7893.0,440,420,90,950,6943.0
2283,12,9,4,3.654616,436.5,7857.0,480,315,120,915,6942.0
2291,12,10,2,3.449173,435.0,7830.0,480,350,60,890,6940.0
2260,12,7,1,4.944349,427.5,7695.0,480,245,30,755,6940.0
2272,12,8,3,3.834027,432.5,7785.0,480,280,90,850,6935.0
2482,13,9,3,3.587693,436.5,7857.0,520,315,90,925,6932.0
1870,10,8,1,4.679947,424.5,7641.0,400,280,30,710,6931.0
1881,10,9,2,3.936102,428.0,7704.0,400,315,60,775,6929.0
2470,13,8,1,4.145751,431.0,7758.0,520,280,30,830,6928.0

Let's do the same, but for revenue (and profit as a tiebreaker) just to compare

In [17]:
sim_results_df.sort_values(by=['revenue', 'profit'], ascending=False).head(25)

,cashiers,servers,ushers,avg_wait,num_customers,revenue,cost_cashiers,cost_servers,cost_ushers,cost_labor,profit
2892,15,10,3,3.566225,440.0,7920.0,600,350,90,1040,6880.0
2513,13,12,4,3.565232,440.0,7920.0,520,420,120,1060,6860.0
2758,14,16,9,3.546591,440.0,7920.0,560,560,270,1390,6530.0
3302,17,11,3,3.456021,439.5,7911.0,680,385,90,1155,6756.0
3135,16,14,6,3.393336,439.5,7911.0,640,490,180,1310,6601.0
2189,11,19,10,3.455114,439.5,7911.0,440,665,300,1405,6506.0
3747,19,15,8,3.568451,439.0,7902.0,760,525,240,1525,6377.0
2112,11,12,3,3.520507,438.5,7893.0,440,420,90,950,6943.0
2894,15,10,5,3.698758,438.5,7893.0,600,350,150,1100,6793.0
2362,12,17,3,3.544056,438.5,7893.0,480,595,90,1165,6728.0
2356,12,16,7,3.564522,438.5,7893.0,480,560,210,1250,6643.0
3306,17,11,7,3.519311,438.5,7893.0,680,385,210,1275,6618.0
2539,13,14,10,3.603304,438.5,7893.0,520,490,300,1310,6583.0
3736,19,14,7,3.636567,438.5,7893.0,760,490,210,1460,6433.0
3549,18,15,10,3.477534,438.5,7893.0,720,525,300,1545,6348.0
2102,11,11,3,3.627143,438.0,7884.0,440,385,90,915,6969.0
3092,16,10,3,3.499829,438.0,7884.0,640,350,90,1080,6804.0
2373,12,18,4,3.361686,438.0,7884.0,480,630,120,1230,6654.0
2554,13,16,5,3.471589,438.0,7884.0,520,560,150,1230,6654.0
2934,15,14,5,3.493776,438.0,7884.0,600,490,150,1240,6644.0
2908,15,11,9,3.551370,438.0,7884.0,600,385,270,1255,6629.0
2358,12,16,9,3.352244,438.0,7884.0,480,560,270,1310,6574.0
3371,17,18,2,3.556061,438.0,7884.0,680,630,60,1370,6514.0
3554,18,16,5,3.470323,438.0,7884.0,720,560,150,1430,6454.0
3709,19,11,10,3.535559,438.0,7884.0,760,385,300,1445,6439.0

## 4.4 Conclusions and recommendations